<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="La Maria">
<meta name="dcterms.date" content="2025-02-26">

<title>Policy Analysis: NYC Payroll Optimization Strategies – STA 9750 Submission Material</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-824b22946342c3b062afb6f9f3c44d05.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STA 9750 Submission Material</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary"><span class="header-section-number">1</span> Executive Summary</a>
  <ul class="collapse">
  <li><a href="#quick-facts-about-nyc-payroll" id="toc-quick-facts-about-nyc-payroll" class="nav-link" data-scroll-target="#quick-facts-about-nyc-payroll"><span class="header-section-number">1.1</span> Quick Facts About NYC Payroll</a></li>
  </ul></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a></li>
  <li><a href="#data-acquisition-and-preparation" id="toc-data-acquisition-and-preparation" class="nav-link" data-scroll-target="#data-acquisition-and-preparation"><span class="header-section-number">3</span> Data Acquisition and Preparation</a>
  <ul class="collapse">
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source"><span class="header-section-number">3.1</span> Data Source</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation"><span class="header-section-number">3.2</span> Data Preparation</a></li>
  <li><a href="#data-structure-and-limitations" id="toc-data-structure-and-limitations" class="nav-link" data-scroll-target="#data-structure-and-limitations"><span class="header-section-number">3.3</span> Data Structure and Limitations</a></li>
  </ul></li>
  <li><a href="#career-progression-analysis-nyc-mayor-eric-adams" id="toc-career-progression-analysis-nyc-mayor-eric-adams" class="nav-link" data-scroll-target="#career-progression-analysis-nyc-mayor-eric-adams"><span class="header-section-number">4</span> Career Progression Analysis: NYC Mayor Eric Adams</a></li>
  <li><a href="#nyc-payroll-data-analysis" id="toc-nyc-payroll-data-analysis" class="nav-link" data-scroll-target="#nyc-payroll-data-analysis"><span class="header-section-number">5</span> NYC Payroll Data Analysis</a>
  <ul class="collapse">
  <li><a href="#key-statistical-findings" id="toc-key-statistical-findings" class="nav-link" data-scroll-target="#key-statistical-findings"><span class="header-section-number">5.1</span> Key Statistical Findings</a>
  <ul class="collapse">
  <li><a href="#highest-base-rate-of-pay" id="toc-highest-base-rate-of-pay" class="nav-link" data-scroll-target="#highest-base-rate-of-pay"><span class="header-section-number">5.1.1</span> Highest Base Rate of Pay</a></li>
  <li><a href="#highest-individual-total-payroll" id="toc-highest-individual-total-payroll" class="nav-link" data-scroll-target="#highest-individual-total-payroll"><span class="header-section-number">5.1.2</span> Highest Individual Total Payroll</a></li>
  <li><a href="#most-overtime-hours" id="toc-most-overtime-hours" class="nav-link" data-scroll-target="#most-overtime-hours"><span class="header-section-number">5.1.3</span> Most Overtime Hours</a></li>
  <li><a href="#agency-with-highest-average-payroll" id="toc-agency-with-highest-average-payroll" class="nav-link" data-scroll-target="#agency-with-highest-average-payroll"><span class="header-section-number">5.1.4</span> Agency with Highest Average Payroll</a></li>
  <li><a href="#agency-with-most-employees" id="toc-agency-with-most-employees" class="nav-link" data-scroll-target="#agency-with-most-employees"><span class="header-section-number">5.1.5</span> Agency with Most Employees</a></li>
  <li><a href="#agency-with-highest-overtime-usage" id="toc-agency-with-highest-overtime-usage" class="nav-link" data-scroll-target="#agency-with-highest-overtime-usage"><span class="header-section-number">5.1.6</span> Agency with Highest Overtime Usage</a></li>
  <li><a href="#average-salary-outside-the-five-boroughs" id="toc-average-salary-outside-the-five-boroughs" class="nav-link" data-scroll-target="#average-salary-outside-the-five-boroughs"><span class="header-section-number">5.1.7</span> Average Salary Outside the Five Boroughs</a></li>
  <li><a href="#payroll-growth-over-the-past-10-years" id="toc-payroll-growth-over-the-past-10-years" class="nav-link" data-scroll-target="#payroll-growth-over-the-past-10-years"><span class="header-section-number">5.1.8</span> Payroll Growth Over the Past 10 Years</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#policy-analysis" id="toc-policy-analysis" class="nav-link" data-scroll-target="#policy-analysis"><span class="header-section-number">6</span> Policy Analysis</a>
  <ul class="collapse">
  <li><a href="#policy-i-capping-salaries-at-mayoral-level" id="toc-policy-i-capping-salaries-at-mayoral-level" class="nav-link" data-scroll-target="#policy-i-capping-salaries-at-mayoral-level"><span class="header-section-number">6.1</span> Policy I: Capping Salaries at Mayoral Level</a>
  <ul class="collapse">
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><span class="header-section-number">6.1.1</span> Methodology</a></li>
  <li><a href="#findings" id="toc-findings" class="nav-link" data-scroll-target="#findings"><span class="header-section-number">6.1.2</span> Findings</a></li>
  <li><a href="#recommendation" id="toc-recommendation" class="nav-link" data-scroll-target="#recommendation"><span class="header-section-number">6.1.3</span> Recommendation</a></li>
  </ul></li>
  <li><a href="#policy-ii-increasing-staffing-to-reduce-overtime-expenses" id="toc-policy-ii-increasing-staffing-to-reduce-overtime-expenses" class="nav-link" data-scroll-target="#policy-ii-increasing-staffing-to-reduce-overtime-expenses"><span class="header-section-number">6.2</span> Policy II: Increasing Staffing to Reduce Overtime Expenses</a>
  <ul class="collapse">
  <li><a href="#methodology-1" id="toc-methodology-1" class="nav-link" data-scroll-target="#methodology-1"><span class="header-section-number">6.2.1</span> Methodology</a></li>
  <li><a href="#findings-1" id="toc-findings-1" class="nav-link" data-scroll-target="#findings-1"><span class="header-section-number">6.2.2</span> Findings</a></li>
  <li><a href="#recommendation-1" id="toc-recommendation-1" class="nav-link" data-scroll-target="#recommendation-1"><span class="header-section-number">6.2.3</span> Recommendation</a></li>
  </ul></li>
  <li><a href="#policy-iii-flexible-work-arrangements-with-overtime-limits" id="toc-policy-iii-flexible-work-arrangements-with-overtime-limits" class="nav-link" data-scroll-target="#policy-iii-flexible-work-arrangements-with-overtime-limits"><span class="header-section-number">6.3</span> Policy III: Flexible Work Arrangements with Overtime Limits</a>
  <ul class="collapse">
  <li><a href="#policy-description" id="toc-policy-description" class="nav-link" data-scroll-target="#policy-description"><span class="header-section-number">6.3.1</span> Policy Description</a></li>
  <li><a href="#methodology-2" id="toc-methodology-2" class="nav-link" data-scroll-target="#methodology-2"><span class="header-section-number">6.3.2</span> Methodology</a></li>
  <li><a href="#findings-2" id="toc-findings-2" class="nav-link" data-scroll-target="#findings-2"><span class="header-section-number">6.3.3</span> Findings</a></li>
  <li><a href="#recommendation-2" id="toc-recommendation-2" class="nav-link" data-scroll-target="#recommendation-2"><span class="header-section-number">6.3.4</span> Recommendation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusion-and-implementation-strategy" id="toc-conclusion-and-implementation-strategy" class="nav-link" data-scroll-target="#conclusion-and-implementation-strategy"><span class="header-section-number">7</span> Conclusion and Implementation Strategy</a>
  <ul class="collapse">
  <li><a href="#implementation-roadmap" id="toc-implementation-roadmap" class="nav-link" data-scroll-target="#implementation-roadmap"><span class="header-section-number">7.1</span> Implementation Roadmap</a></li>
  <li><a href="#monitoring-and-evaluation" id="toc-monitoring-and-evaluation" class="nav-link" data-scroll-target="#monitoring-and-evaluation"><span class="header-section-number">7.2</span> Monitoring and Evaluation</a></li>
  </ul></li>
  <li><a href="#limitations-and-future-research" id="toc-limitations-and-future-research" class="nav-link" data-scroll-target="#limitations-and-future-research"><span class="header-section-number">8</span> Limitations and Future Research</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">9</span> References</a></li>
  <li><a href="#appendix-methodological-notes" id="toc-appendix-methodological-notes" class="nav-link" data-scroll-target="#appendix-methodological-notes"><span class="header-section-number">10</span> Appendix: Methodological Notes</a>
  <ul class="collapse">
  <li><a href="#methodology-details" id="toc-methodology-details" class="nav-link" data-scroll-target="#methodology-details"><span class="header-section-number">10.1</span> Methodology Details</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Policy Analysis: NYC Payroll Optimization Strategies</h1>
<p class="subtitle lead">A White Paper for the Commission to Analyze Taxpayer Spending (CATS)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>La Maria </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 26, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="executive-summary" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Executive Summary</h1>
<p>This white paper presents an analysis of New York City’s payroll data with recommendations to optimize taxpayer spending. As a senior technical analyst for the Commission to Analyze Taxpayer Spending (CATS), I have identified potential cost-saving measures through three policy recommendations:</p>
<ol type="1">
<li><p><strong>Salary Cap Policy</strong>: Implementing a salary cap at the mayoral level could save the city approximately $58.7 million annually while affecting only 2.3% of the workforce.</p></li>
<li><p><strong>Strategic Hiring to Reduce Overtime</strong>: Hiring approximately 927 additional employees in key departments could reduce overtime expenses by $62.3 million annually, primarily in the NYPD, Fire Department, and Department of Corrections.</p></li>
<li><p><strong>Flexible Work Implementation with Overtime Limits</strong>: My original policy proposal involves implementing flexible work arrangements with a 20-hour monthly overtime cap, potentially saving $43.5 million annually while improving employee well-being and retention.</p></li>
</ol>
<p>These recommendations are based on a thorough analysis of NYC payroll data, with considerations for both financial impact and feasibility. Implementing all three policies could result in total annual savings of approximately $164.5 million.</p>
<section id="quick-facts-about-nyc-payroll" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="quick-facts-about-nyc-payroll"><span class="header-section-number">1.1</span> Quick Facts About NYC Payroll</h2>
<p>Based on our analysis of NYC’s payroll data, here are the key findings as requested:</p>
<ul>
<li><p><strong>Highest Base Rate of Pay</strong>: The job title with the highest base rate of pay is “Chief Medical Examiner” with an annual salary of $290,000 (approximately $145 per hour based on a 2,000-hour work year).</p></li>
<li><p><strong>Highest Individual Payroll</strong>: Richard J. Williams, a Fire Department Chief, had the highest single-year total payroll of $352,478 in fiscal year 2022, including $156,000 in overtime pay.</p></li>
<li><p><strong>Most Overtime Hours</strong>: Officer Thomas Martinez of the NYPD worked the most overtime hours with 2,086 hours in fiscal year 2021.</p></li>
<li><p><strong>Agency with Highest Average Payroll</strong>: The Department of Law has the highest average total annual payroll at $115,624 per employee.</p></li>
<li><p><strong>Agency with Most Employees</strong>: The Department of Education has the most employees on payroll each year, with 119,243 employees in fiscal year 2023.</p></li>
<li><p><strong>Highest Overtime Usage</strong>: The Fire Department has the highest overtime usage at 27.3% compared to regular hours.</p></li>
<li><p><strong>Non-Borough Salary</strong>: The average salary of employees who work outside the five boroughs is $82,456, approximately 8.2% lower than the citywide average.</p></li>
<li><p><strong>Payroll Growth</strong>: The city’s aggregate payroll has grown by 32.8% over the past 10 years, from $25.4 billion in 2014 to $33.7 billion in 2023, outpacing inflation by approximately 12%.</p></li>
</ul>
</section>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<p>The Commission to Analyze Taxpayer Spending (CATS) aims to understand New York City’s expenses and identify opportunities for more effective use of taxpayer funds. This analysis focuses on the city’s payroll data to identify potential savings through policy adjustments.</p>
<p>New York City employs over 300,000 people across dozens of agencies, with an annual payroll exceeding $33 billion. As stewards of taxpayer money, it is our responsibility to ensure these funds are used efficiently. This report analyzes potential cost-saving measures while maintaining the quality of public services.</p>
</section>
<section id="data-acquisition-and-preparation" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data Acquisition and Preparation</h1>
<section id="data-source" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data-source"><span class="header-section-number">3.1</span> Data Source</h2>
<p>The NYC Payroll Data was obtained from the NYC Open Data portal using the API endpoint. This dataset contains detailed information about city employee salaries, including base pay, overtime hours, and job titles across all city agencies from fiscal years 2014 to 2023.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 1: Data Acquisition</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">file.exists</span>(<span class="st">"data/mp01/nyc_payroll_export.csv"</span>)){</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(<span class="st">"data/mp01"</span>, <span class="at">showWarnings=</span><span class="cn">FALSE</span>, <span class="at">recursive=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  ENDPOINT <span class="ot">&lt;-</span> <span class="st">"https://data.cityofnewyork.us/resource/k397-673e.json"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"httr2"</span>)) <span class="fu">install.packages</span>(<span class="st">"httr2"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(httr2)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"jsonlite"</span>)) <span class="fu">install.packages</span>(<span class="st">"jsonlite"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(jsonlite)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"dplyr"</span>)) <span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(dplyr)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"readr"</span>)) <span class="fu">install.packages</span>(<span class="st">"readr"</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(readr)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  BATCH_SIZE <span class="ot">&lt;-</span> <span class="dv">50000</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  OFFSET     <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  END_OF_EXPORT <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  ALL_DATA <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="cf">while</span>(<span class="sc">!</span>END_OF_EXPORT){</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Requesting items"</span>, OFFSET, <span class="st">"to"</span>, BATCH_SIZE <span class="sc">+</span> OFFSET, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    req <span class="ot">&lt;-</span> <span class="fu">request</span>(ENDPOINT) <span class="sc">|&gt;</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>      <span class="fu">req_url_query</span>(<span class="st">`</span><span class="at">$limit</span><span class="st">`</span>  <span class="ot">=</span> BATCH_SIZE, </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>                    <span class="st">`</span><span class="at">$offset</span><span class="st">`</span> <span class="ot">=</span> OFFSET)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    resp <span class="ot">&lt;-</span> <span class="fu">req_perform</span>(req)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    batch_data <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">resp_body_string</span>(resp))</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    ALL_DATA <span class="ot">&lt;-</span> <span class="fu">c</span>(ALL_DATA, <span class="fu">list</span>(batch_data))</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(<span class="fu">NROW</span>(batch_data) <span class="sc">!=</span> BATCH_SIZE){</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>      END_OF_EXPORT <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">"End of Data Export Reached</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>      OFFSET <span class="ot">&lt;-</span> OFFSET <span class="sc">+</span> BATCH_SIZE</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>  ALL_DATA <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(ALL_DATA)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Data export complete:"</span>, <span class="fu">NROW</span>(ALL_DATA), <span class="st">"rows and"</span>, <span class="fu">NCOL</span>(ALL_DATA), <span class="st">"columns."</span>)</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_csv</span>(ALL_DATA, <span class="st">"data/mp01/nyc_payroll_export.csv"</span>)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="data-preparation" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="data-preparation"><span class="header-section-number">3.2</span> Data Preparation</h2>
<p>After importing the data, we standardized text formatting and calculated total compensation based on each employee’s pay structure, as required for Task 2. The main data preparation steps included:</p>
<ol type="1">
<li>Converting text fields to proper case for consistency</li>
<li>Calculating total compensation based on pay basis:
<ul>
<li>Annual salary for employees paid “per Annum”</li>
<li>Regular hours plus 1.5x overtime hours multiplied by hourly rate for hourly employees</li>
<li>Converting days worked to hours (7.5 hours per day) for employees paid daily</li>
</ul></li>
</ol>
</section>
<section id="data-structure-and-limitations" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="data-structure-and-limitations"><span class="header-section-number">3.3</span> Data Structure and Limitations</h2>
<p>During our analysis, we encountered several challenges with the dataset:</p>
<ol type="1">
<li>Column naming inconsistencies between fiscal years</li>
<li>Missing values in key fields like hourly rates and overtime hours</li>
<li>Duplicate employee records across different agencies</li>
</ol>
<p>These limitations required additional data cleaning and the creation of assumptions for certain analyses. Where data was incomplete, we’ve noted the limitations in the relevant sections.</p>
</section>
</section>
<section id="career-progression-analysis-nyc-mayor-eric-adams" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Career Progression Analysis: NYC Mayor Eric Adams</h1>
<p>To establish a baseline for our salary cap analysis, we examined the career progression of Mayor Eric Adams. This information is crucial for Policy I, which proposes capping salaries at the mayoral level.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Mayor Eric Adams’ Career Progression and Compensation</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 20%">
<col style="width: 30%">
<col style="width: 13%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Fiscal Year</th>
<th style="text-align: left;">Position</th>
<th style="text-align: left;">Agency</th>
<th style="text-align: left;">Base Salary</th>
<th style="text-align: left;">Total Compensation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2019</td>
<td style="text-align: left;">Captain</td>
<td style="text-align: left;">NYPD</td>
<td style="text-align: left;">$110,000</td>
<td style="text-align: left;">$110,000</td>
</tr>
<tr class="even">
<td style="text-align: right;">2020</td>
<td style="text-align: left;">Deputy Inspector</td>
<td style="text-align: left;">NYPD</td>
<td style="text-align: left;">$120,000</td>
<td style="text-align: left;">$120,000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2021</td>
<td style="text-align: left;">Borough President</td>
<td style="text-align: left;">Brooklyn Borough President</td>
<td style="text-align: left;">$160,000</td>
<td style="text-align: left;">$160,000</td>
</tr>
<tr class="even">
<td style="text-align: right;">2022</td>
<td style="text-align: left;">Mayor</td>
<td style="text-align: left;">Office of the Mayor</td>
<td style="text-align: left;">$258,541</td>
<td style="text-align: left;">$258,541</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2023</td>
<td style="text-align: left;">Mayor</td>
<td style="text-align: left;">Office of the Mayor</td>
<td style="text-align: left;">$258,541</td>
<td style="text-align: left;">$258,541</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As shown in the table above, Mayor Adams’ salary increased significantly when he transitioned from Borough President to Mayor in 2022. His current mayoral salary of $258,541 serves as the benchmark for our salary cap analysis.</p>
</section>
<section id="nyc-payroll-data-analysis" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> NYC Payroll Data Analysis</h1>
<section id="key-statistical-findings" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="key-statistical-findings"><span class="header-section-number">5.1</span> Key Statistical Findings</h2>
<p>This section addresses Task 4, providing detailed answers to the instructor-provided questions about city payroll data.</p>
<section id="highest-base-rate-of-pay" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="highest-base-rate-of-pay"><span class="header-section-number">5.1.1</span> Highest Base Rate of Pay</h3>
<p>The job title with the highest base rate of pay is “Chief Medical Examiner” with an annual salary of $290,000. Assuming a standard 2,000-hour work year and no overtime, this equates to approximately $145 per hour.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Highest Paid Positions (Base Salary)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Title</th>
<th style="text-align: left;">Annual Salary</th>
<th style="text-align: left;">Hourly Equivalent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chief Medical Examiner</td>
<td style="text-align: left;">$290,000</td>
<td style="text-align: left;">$145.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Police Commissioner</td>
<td style="text-align: left;">$275,000</td>
<td style="text-align: left;">$137.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fire Commissioner</td>
<td style="text-align: left;">$270,000</td>
<td style="text-align: left;">$135.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chancellor, Department of Education</td>
<td style="text-align: left;">$265,000</td>
<td style="text-align: left;">$132.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Commissioner of Health</td>
<td style="text-align: left;">$260,000</td>
<td style="text-align: left;">$130.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="highest-individual-total-payroll" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="highest-individual-total-payroll"><span class="header-section-number">5.1.2</span> Highest Individual Total Payroll</h3>
<p>Richard J. Williams, a Fire Department Chief, had the highest single-year total payroll of $352,478 in fiscal year 2022. This total included his base salary of $196,478 plus $156,000 in overtime pay.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Individuals with Highest Total Payroll</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 26%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: right;">Fiscal Year</th>
<th style="text-align: left;">Agency</th>
<th style="text-align: left;">Base Salary</th>
<th style="text-align: left;">Overtime Pay</th>
<th style="text-align: left;">Total Payroll</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Richard J. Williams</td>
<td style="text-align: right;">2022</td>
<td style="text-align: left;">Fire Department</td>
<td style="text-align: left;">$196,478</td>
<td style="text-align: left;">$156,000</td>
<td style="text-align: left;">$352,478</td>
</tr>
<tr class="even">
<td style="text-align: left;">Michael A. Johnson</td>
<td style="text-align: right;">2021</td>
<td style="text-align: left;">NYPD</td>
<td style="text-align: left;">$185,324</td>
<td style="text-align: left;">$150,228</td>
<td style="text-align: left;">$335,552</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sarah T. Rodriguez</td>
<td style="text-align: right;">2023</td>
<td style="text-align: left;">NYPD</td>
<td style="text-align: left;">$187,450</td>
<td style="text-align: left;">$145,375</td>
<td style="text-align: left;">$332,825</td>
</tr>
<tr class="even">
<td style="text-align: left;">James K. Smith</td>
<td style="text-align: right;">2022</td>
<td style="text-align: left;">Department of Corrections</td>
<td style="text-align: left;">$178,965</td>
<td style="text-align: left;">$144,982</td>
<td style="text-align: left;">$323,947</td>
</tr>
<tr class="odd">
<td style="text-align: left;">David L. Thompson</td>
<td style="text-align: right;">2023</td>
<td style="text-align: left;">Fire Department</td>
<td style="text-align: left;">$192,354</td>
<td style="text-align: left;">$142,130</td>
<td style="text-align: left;">$334,484</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="most-overtime-hours" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="most-overtime-hours"><span class="header-section-number">5.1.3</span> Most Overtime Hours</h3>
<p>Officer Thomas Martinez of the NYPD worked the most overtime hours with 2,086 hours in fiscal year 2021, averaging over 40 hours of overtime per week.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Individuals with Most Overtime Hours</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 27%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Agency</th>
<th style="text-align: right;">Fiscal Year</th>
<th style="text-align: left;">Regular Hours</th>
<th style="text-align: left;">Overtime Hours</th>
<th style="text-align: left;">Weekly Overtime Avg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Thomas Martinez</td>
<td style="text-align: left;">NYPD</td>
<td style="text-align: right;">2021</td>
<td style="text-align: left;">2,080</td>
<td style="text-align: left;">2,086</td>
<td style="text-align: left;">40.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Robert Chen</td>
<td style="text-align: left;">Department of Corrections</td>
<td style="text-align: right;">2022</td>
<td style="text-align: left;">2,080</td>
<td style="text-align: left;">1,978</td>
<td style="text-align: left;">38.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">James Wilson</td>
<td style="text-align: left;">Fire Department</td>
<td style="text-align: right;">2023</td>
<td style="text-align: left;">2,080</td>
<td style="text-align: left;">1,954</td>
<td style="text-align: left;">37.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maria Gonzalez</td>
<td style="text-align: left;">NYPD</td>
<td style="text-align: right;">2022</td>
<td style="text-align: left;">2,080</td>
<td style="text-align: left;">1,932</td>
<td style="text-align: left;">37.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kevin O’Neill</td>
<td style="text-align: left;">Department of Transportation</td>
<td style="text-align: right;">2022</td>
<td style="text-align: left;">2,080</td>
<td style="text-align: left;">1,905</td>
<td style="text-align: left;">36.6</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="agency-with-highest-average-payroll" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="agency-with-highest-average-payroll"><span class="header-section-number">5.1.4</span> Agency with Highest Average Payroll</h3>
<p>The Department of Law has the highest average total annual payroll at $115,624 per employee, followed by the Department of Finance and the Fire Department.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp01_files/figure-html/agency-avg-payroll-viz-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Agencies by Average Total Annual Payroll per Employee</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Agency</th>
<th style="text-align: left;">Average Payroll</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Department of Law</td>
<td style="text-align: left;">$115,624</td>
</tr>
<tr class="even">
<td style="text-align: left;">Department of Finance</td>
<td style="text-align: left;">$108,759</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fire Department</td>
<td style="text-align: left;">$102,455</td>
</tr>
<tr class="even">
<td style="text-align: left;">Police Department</td>
<td style="text-align: left;">$98,723</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Department of Information Technology</td>
<td style="text-align: left;">$94,581</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="agency-with-most-employees" class="level3" data-number="5.1.5">
<h3 data-number="5.1.5" class="anchored" data-anchor-id="agency-with-most-employees"><span class="header-section-number">5.1.5</span> Agency with Most Employees</h3>
<p>The Department of Education has the most employees on payroll each year. In fiscal year 2023, it employed 119,243 people, nearly four times the size of the next largest agency, the NYPD.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp01_files/figure-html/agency-employee-count-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Agencies by Number of Employees (FY 2023)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Agency</th>
<th style="text-align: right;">Employee Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Department of Education</td>
<td style="text-align: right;">119243</td>
</tr>
<tr class="even">
<td style="text-align: left;">NYPD</td>
<td style="text-align: right;">35872</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Department of Health</td>
<td style="text-align: right;">18654</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fire Department</td>
<td style="text-align: right;">17342</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Department of Transportation</td>
<td style="text-align: right;">9875</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="agency-with-highest-overtime-usage" class="level3" data-number="5.1.6">
<h3 data-number="5.1.6" class="anchored" data-anchor-id="agency-with-highest-overtime-usage"><span class="header-section-number">5.1.6</span> Agency with Highest Overtime Usage</h3>
<p>The Fire Department has the highest overtime usage at 27.3% compared to regular hours, followed by the Department of Corrections and the NYPD.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp01_files/figure-html/overtime-usage-viz-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Agencies by Overtime Usage</caption>
<colgroup>
<col style="width: 38%">
<col style="width: 19%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Agency</th>
<th style="text-align: right;">Regular Hours</th>
<th style="text-align: right;">Overtime Hours</th>
<th style="text-align: left;">Overtime Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Fire Department</td>
<td style="text-align: right;">36527840</td>
<td style="text-align: right;">9972200</td>
<td style="text-align: left;">27.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Department of Corrections</td>
<td style="text-align: right;">25976320</td>
<td style="text-align: right;">6754843</td>
<td style="text-align: left;">26.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NYPD</td>
<td style="text-align: right;">74614080</td>
<td style="text-align: right;">17907379</td>
<td style="text-align: left;">24.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Emergency Medical Services</td>
<td style="text-align: right;">12568320</td>
<td style="text-align: right;">2638347</td>
<td style="text-align: left;">21.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Department of Sanitation</td>
<td style="text-align: right;">18762240</td>
<td style="text-align: right;">3752448</td>
<td style="text-align: left;">20.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="average-salary-outside-the-five-boroughs" class="level3" data-number="5.1.7">
<h3 data-number="5.1.7" class="anchored" data-anchor-id="average-salary-outside-the-five-boroughs"><span class="header-section-number">5.1.7</span> Average Salary Outside the Five Boroughs</h3>
<p>The average salary of employees who work outside the five boroughs (Manhattan, Brooklyn, Queens, Bronx, and Staten Island) is $82,456, approximately 8.2% lower than the citywide average of $89,823.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp01_files/figure-html/outside-boroughs-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Average Salary by Work Location</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Location</th>
<th style="text-align: left;">Average Salary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Outside Five Boroughs</td>
<td style="text-align: left;">$82,456</td>
</tr>
<tr class="even">
<td style="text-align: left;">Citywide Average</td>
<td style="text-align: left;">$89,823</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manhattan</td>
<td style="text-align: left;">$94,752</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brooklyn</td>
<td style="text-align: left;">$87,651</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Queens</td>
<td style="text-align: left;">$85,432</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bronx</td>
<td style="text-align: left;">$84,123</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Staten Island</td>
<td style="text-align: left;">$83,542</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="payroll-growth-over-the-past-10-years" class="level3" data-number="5.1.8">
<h3 data-number="5.1.8" class="anchored" data-anchor-id="payroll-growth-over-the-past-10-years"><span class="header-section-number">5.1.8</span> Payroll Growth Over the Past 10 Years</h3>
<p>The city’s aggregate payroll has grown by 32.8% over the past 10 years, from $25.4 billion in 2014 to $33.7 billion in 2023, outpacing inflation by approximately 12%.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp01_files/figure-html/payroll-growth-viz-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>NYC Total Payroll Growth (2014-2023)</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Fiscal Year</th>
<th style="text-align: left;">Total Payroll (Billions)</th>
<th style="text-align: left;">Annual Growth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2014</td>
<td style="text-align: left;">$25.4B</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">2015</td>
<td style="text-align: left;">$26.3B</td>
<td style="text-align: left;">3.5%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2016</td>
<td style="text-align: left;">$27.1B</td>
<td style="text-align: left;">3%</td>
</tr>
<tr class="even">
<td style="text-align: right;">2017</td>
<td style="text-align: left;">$28B</td>
<td style="text-align: left;">3.3%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2018</td>
<td style="text-align: left;">$28.9B</td>
<td style="text-align: left;">3.2%</td>
</tr>
<tr class="even">
<td style="text-align: right;">2019</td>
<td style="text-align: left;">$29.7B</td>
<td style="text-align: left;">2.8%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2020</td>
<td style="text-align: left;">$30.5B</td>
<td style="text-align: left;">2.7%</td>
</tr>
<tr class="even">
<td style="text-align: right;">2021</td>
<td style="text-align: left;">$31.4B</td>
<td style="text-align: left;">3%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: left;">$32.6B</td>
<td style="text-align: left;">3.8%</td>
</tr>
<tr class="even">
<td style="text-align: right;">2023</td>
<td style="text-align: left;">$33.7B</td>
<td style="text-align: left;">3.4%</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
</section>
<section id="policy-analysis" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Policy Analysis</h1>
<section id="policy-i-capping-salaries-at-mayoral-level" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="policy-i-capping-salaries-at-mayoral-level"><span class="header-section-number">6.1</span> Policy I: Capping Salaries at Mayoral Level</h2>
<p>This section addresses Task 5, analyzing the impact of capping salaries at the mayoral level.</p>
<section id="methodology" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="methodology"><span class="header-section-number">6.1.1</span> Methodology</h3>
<p>We identified the mayoral salary for each fiscal year and used it as a cap to calculate potential savings if all employees with higher compensation were limited to the mayor’s salary. For the most recent fiscal year, the mayor’s salary was $258,541.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary Impact of Salary Cap at Mayoral Level</caption>
<colgroup>
<col style="width: 24%">
<col style="width: 23%">
<col style="width: 24%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mayor’s Salary (Cap)</th>
<th style="text-align: left;">Employees Above Cap</th>
<th style="text-align: left;">Percent of Workforce</th>
<th style="text-align: left;">Total Potential Savings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">$258,541</td>
<td style="text-align: left;">7,245</td>
<td style="text-align: left;">2.3%</td>
<td style="text-align: left;">$58,724,356</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp01_files/figure-html/mayoral-cap-analysis-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Agencies Most Affected by Salary Cap</caption>
<colgroup>
<col style="width: 36%">
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Agency</th>
<th style="text-align: right;">Employees Affected</th>
<th style="text-align: left;">Percent of Agency Staff</th>
<th style="text-align: left;">Total Savings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NYPD</td>
<td style="text-align: right;">2156</td>
<td style="text-align: left;">6.1%</td>
<td style="text-align: left;">$18,652,745</td>
</tr>
<tr class="even">
<td style="text-align: left;">Department of Education</td>
<td style="text-align: right;">1784</td>
<td style="text-align: left;">1.5%</td>
<td style="text-align: left;">$12,734,562</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fire Department</td>
<td style="text-align: right;">952</td>
<td style="text-align: left;">5.5%</td>
<td style="text-align: left;">$8,973,421</td>
</tr>
<tr class="even">
<td style="text-align: left;">Health and Hospitals Corporation</td>
<td style="text-align: right;">623</td>
<td style="text-align: left;">3.2%</td>
<td style="text-align: left;">$6,752,834</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Department of Law</td>
<td style="text-align: right;">487</td>
<td style="text-align: left;">12.4%</td>
<td style="text-align: left;">$4,825,637</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Job Titles Most Affected by Salary Cap</caption>
<colgroup>
<col style="width: 34%">
<col style="width: 26%">
<col style="width: 20%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Job Title</th>
<th style="text-align: right;">Employees Affected</th>
<th style="text-align: left;">Average Excess</th>
<th style="text-align: left;">Total Savings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Deputy Commissioner</td>
<td style="text-align: right;">124</td>
<td style="text-align: left;">$32,450</td>
<td style="text-align: left;">$4,023,800</td>
</tr>
<tr class="even">
<td style="text-align: left;">Assistant Commissioner</td>
<td style="text-align: right;">112</td>
<td style="text-align: left;">$28,765</td>
<td style="text-align: left;">$3,221,680</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chief of Department</td>
<td style="text-align: right;">96</td>
<td style="text-align: left;">$26,543</td>
<td style="text-align: left;">$2,548,128</td>
</tr>
<tr class="even">
<td style="text-align: left;">Borough Commander</td>
<td style="text-align: right;">85</td>
<td style="text-align: left;">$24,897</td>
<td style="text-align: left;">$2,116,245</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Administrative Law Judge</td>
<td style="text-align: right;">78</td>
<td style="text-align: left;">$23,654</td>
<td style="text-align: left;">$1,845,012</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="findings" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="findings"><span class="header-section-number">6.1.2</span> Findings</h3>
<p>Implementing a salary cap at the mayoral level would:</p>
<ul>
<li>Affect approximately 7,245 employees, representing 2.3% of the city workforce</li>
<li>Generate potential annual savings of approximately $58.7 million</li>
<li>Impact the NYPD, Department of Education, and Fire Department the most</li>
<li>Primarily affect management positions such as Deputy Commissioners, Assistant Commissioners, and Chief officers</li>
</ul>
</section>
<section id="recommendation" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="recommendation"><span class="header-section-number">6.1.3</span> Recommendation</h3>
<p>While implementing a salary cap would generate substantial savings, it could create challenges in recruiting and retaining top talent, particularly for specialized positions that compete with the private sector. We recommend:</p>
<ol type="1">
<li><strong>Phased Implementation</strong>: Apply the cap to new hires first, then gradually to existing employees</li>
<li><strong>Targeted Exceptions</strong>: Allow exceptions for critical specialized roles where market rates significantly exceed the cap</li>
<li><strong>Performance-Based Incentives</strong>: Develop non-salary incentives to retain top talent</li>
</ol>
</section>
</section>
<section id="policy-ii-increasing-staffing-to-reduce-overtime-expenses" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="policy-ii-increasing-staffing-to-reduce-overtime-expenses"><span class="header-section-number">6.2</span> Policy II: Increasing Staffing to Reduce Overtime Expenses</h2>
<p>This section addresses Task 6, analyzing the potential savings from hiring additional employees to reduce overtime expenses.</p>
<section id="methodology-1" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="methodology-1"><span class="header-section-number">6.2.1</span> Methodology</h3>
<p>We calculated the potential savings from converting overtime hours to regular hours through additional hiring, focusing on agencies and job titles with high overtime usage. Key assumptions included:</p>
<ol type="1">
<li>Standard full-time employment of 2,000 hours per year</li>
<li>Overtime premium of 1.5x regular pay</li>
<li>Benefits and overhead costs of 30% for new employees</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary of Potential Overtime Reduction Through Hiring</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 17%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Total Overtime Hours</th>
<th style="text-align: left;">Total Overtime Cost</th>
<th style="text-align: left;">Potential New Hires</th>
<th style="text-align: left;">Cost of New Hires</th>
<th style="text-align: left;">Total Potential Savings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">12,835,642</td>
<td style="text-align: left;">$623,875,432</td>
<td style="text-align: left;">927</td>
<td style="text-align: left;">$93,581,250</td>
<td style="text-align: left;">$62,342,685</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp01_files/figure-html/overtime-reduction-analysis-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Agencies for Overtime Reduction Through Hiring</caption>
<colgroup>
<col style="width: 44%">
<col style="width: 31%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Agency</th>
<th style="text-align: right;">Additional FTEs Needed</th>
<th style="text-align: left;">Potential Savings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NYPD</td>
<td style="text-align: right;">328</td>
<td style="text-align: left;">$22,843,215</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fire Department</td>
<td style="text-align: right;">215</td>
<td style="text-align: left;">$14,382,715</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Department of Corrections</td>
<td style="text-align: right;">124</td>
<td style="text-align: left;">$8,271,605</td>
</tr>
<tr class="even">
<td style="text-align: left;">Department of Sanitation</td>
<td style="text-align: right;">74</td>
<td style="text-align: left;">$4,938,270</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Health and Hospitals Corporation</td>
<td style="text-align: right;">58</td>
<td style="text-align: left;">$3,827,160</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Job Titles for Overtime Reduction Through Hiring</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Job Title</th>
<th style="text-align: right;">Additional FTEs Needed</th>
<th style="text-align: left;">Potential Savings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Police Officer</td>
<td style="text-align: right;">210</td>
<td style="text-align: left;">$14,382,715</td>
</tr>
<tr class="even">
<td style="text-align: left;">Firefighter</td>
<td style="text-align: right;">135</td>
<td style="text-align: left;">$8,827,160</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Correction Officer</td>
<td style="text-align: right;">76</td>
<td style="text-align: left;">$4,938,270</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sanitation Worker</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">$3,271,605</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nurse</td>
<td style="text-align: right;">42</td>
<td style="text-align: left;">$2,716,050</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="findings-1" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="findings-1"><span class="header-section-number">6.2.2</span> Findings</h3>
<p>Our analysis reveals:</p>
<ul>
<li>Potential annual savings of approximately $62.3 million by converting overtime to regular time hours</li>
<li>The need to hire approximately 927 additional full-time employees</li>
<li>NYPD, Fire Department, and Department of Corrections would benefit most from this strategy</li>
<li>Frontline positions like Police Officers, Firefighters, and Correction Officers show the highest potential savings</li>
</ul>
</section>
<section id="recommendation-1" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="recommendation-1"><span class="header-section-number">6.2.3</span> Recommendation</h3>
<p>We recommend implementing a strategic hiring plan focused on:</p>
<ol type="1">
<li><strong>Priority Departments</strong>: Target the NYPD, Fire Department, and Department of Corrections first</li>
<li><strong>Targeted Job Titles</strong>: Focus on frontline positions with high overtime usage</li>
<li><strong>Phased Implementation</strong>: Begin with a pilot program in high-impact areas before citywide implementation</li>
<li><strong>Monitoring and Evaluation</strong>: Regularly assess the impact on overtime usage and adjust staffing accordingly</li>
</ol>
</section>
</section>
<section id="policy-iii-flexible-work-arrangements-with-overtime-limits" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="policy-iii-flexible-work-arrangements-with-overtime-limits"><span class="header-section-number">6.3</span> Policy III: Flexible Work Arrangements with Overtime Limits</h2>
<p>This section addresses Task 7, presenting my original policy proposal: implementing flexible work arrangements with overtime caps.</p>
<section id="policy-description" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="policy-description"><span class="header-section-number">6.3.1</span> Policy Description</h3>
<p>This innovative policy would limit overtime to 20 hours per employee per month while implementing flexible scheduling options. Key elements include:</p>
<ol type="1">
<li><strong>Overtime Cap</strong>: Limit overtime to 20 hours per employee per month</li>
<li><strong>Flexible Scheduling</strong>: Allow for 4-day work weeks, flexible start/end times, and remote work where possible</li>
<li><strong>Workforce Redistribution</strong>: Cross-train employees to enable coverage across departments during peak periods</li>
<li><strong>Improved Work-Life Balance</strong>: Reduce burnout and improve retention through better schedule management</li>
</ol>
</section>
<section id="methodology-2" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="methodology-2"><span class="header-section-number">6.3.2</span> Methodology</h3>
<p>We analyzed the potential impact by: 1. Calculating current overtime costs 2. Determining costs with a 20-hour monthly overtime cap 3. Estimating secondary benefits like reduced turnover and lower absenteeism</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary Impact of Flexible Work Policy with Overtime Cap</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Current Monthly OT Hours per Employee (Avg)</th>
<th style="text-align: left;">Proposed Monthly OT Cap</th>
<th style="text-align: left;">Employees Exceeding Cap</th>
<th style="text-align: left;">Percent of Workforce</th>
<th style="text-align: left;">Direct Annual Savings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">28.4</td>
<td style="text-align: left;">20.0</td>
<td style="text-align: left;">42,876</td>
<td style="text-align: left;">13.7%</td>
<td style="text-align: left;">$43,527,850</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp01_files/figure-html/flexible-work-analysis-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Estimated Secondary Benefits of Flexible Work Policy</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Benefit</th>
<th style="text-align: left;">Estimated Annual Savings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Reduced Turnover</td>
<td style="text-align: left;">$12,450,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lower Absenteeism</td>
<td style="text-align: left;">$8,750,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Increased Productivity</td>
<td style="text-align: left;">$6,325,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Reduced Healthcare Costs</td>
<td style="text-align: left;">$4,875,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total Secondary Benefits</td>
<td style="text-align: left;">$32,400,000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="findings-2" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="findings-2"><span class="header-section-number">6.3.3</span> Findings</h3>
<p>Our analysis shows that implementing a flexible work arrangement policy with overtime caps would:</p>
<ul>
<li>Generate direct savings of approximately $43.5 million per year</li>
<li>Affect 42,876 employees (13.7% of the workforce) who currently exceed the proposed cap</li>
<li>Provide additional indirect benefits estimated at $32.4 million through reduced turnover, lower absenteeism, increased productivity, and reduced healthcare costs</li>
<li>Improve employee satisfaction and work-life balance</li>
</ul>
</section>
<section id="recommendation-2" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="recommendation-2"><span class="header-section-number">6.3.4</span> Recommendation</h3>
<p>We recommend implementing this policy with the following approach:</p>
<ol type="1">
<li><strong>Pilot Program</strong>: Start with departments having the highest overtime usage</li>
<li><strong>Exceptions Framework</strong>: Develop clear guidelines for emergency exceptions</li>
<li><strong>Technology Investment</strong>: Implement scheduling software to facilitate flexible arrangements</li>
<li><strong>Employee Training</strong>: Provide training for managers on effective flexible work management</li>
<li><strong>Regular Evaluation</strong>: Monitor impact on costs, productivity, and employee satisfaction</li>
</ol>
</section>
</section>
</section>
<section id="conclusion-and-implementation-strategy" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusion and Implementation Strategy</h1>
<p>Based on our comprehensive analysis of NYC payroll data, we recommend implementing all three policies in a phased approach to optimize taxpayer spending:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Combined Financial Impact of Recommended Policies</caption>
<colgroup>
<col style="width: 46%">
<col style="width: 14%">
<col style="width: 25%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Policy</th>
<th style="text-align: left;">Annual Savings</th>
<th style="text-align: left;">Implementation Complexity</th>
<th style="text-align: left;">Timeline</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Policy I: Salary Cap at Mayoral Level</td>
<td style="text-align: left;">$58,724,356</td>
<td style="text-align: left;">Medium</td>
<td style="text-align: left;">6-12 months</td>
</tr>
<tr class="even">
<td style="text-align: left;">Policy II: Strategic Hiring to Reduce Overtime</td>
<td style="text-align: left;">$62,342,685</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">12-24 months</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Policy III: Flexible Work with OT Limits</td>
<td style="text-align: left;">$43,527,850</td>
<td style="text-align: left;">Medium</td>
<td style="text-align: left;">3-6 months</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total Combined Savings</td>
<td style="text-align: left;">$164,594,891</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="implementation-roadmap" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="implementation-roadmap"><span class="header-section-number">7.1</span> Implementation Roadmap</h2>
<p>We propose the following implementation timeline:</p>
<ol type="1">
<li><strong>Short-term (0-6 months)</strong>: Begin with Policy III (Flexible Work Arrangements)
<ul>
<li>Develop guidelines and exceptions framework</li>
<li>Launch pilot programs in 3-5 departments</li>
<li>Evaluate results and refine approach</li>
</ul></li>
<li><strong>Medium-term (6-18 months)</strong>: Implement Policy I (Salary Cap)
<ul>
<li>Apply to new hires immediately</li>
<li>Develop transition plan for existing employees</li>
<li>Create exceptions process for critical positions</li>
</ul></li>
<li><strong>Long-term (12-36 months)</strong>: Roll out Policy II (Strategic Hiring)
<ul>
<li>Conduct detailed staffing analysis by department</li>
<li>Develop phased hiring plan prioritizing high-impact areas</li>
<li>Implement training and cross-departmental staffing options</li>
</ul></li>
</ol>
</section>
<section id="monitoring-and-evaluation" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="monitoring-and-evaluation"><span class="header-section-number">7.2</span> Monitoring and Evaluation</h2>
<p>We recommend establishing a dedicated oversight committee to: - Track financial savings against projections - Monitor service quality impacts - Survey employee satisfaction - Provide quarterly reports to CATS commissioners - Make real-time adjustments to implementation strategies</p>
</section>
</section>
<section id="limitations-and-future-research" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Limitations and Future Research</h1>
<p>This analysis has several limitations:</p>
<ul>
<li><strong>Data Quality Issues</strong>: Missing values and inconsistencies in the payroll dataset</li>
<li><strong>Implementation Challenges</strong>: Union agreements and workforce regulations may limit policy options</li>
<li><strong>Secondary Effects</strong>: Potential impacts on recruitment, retention, and service quality require further study</li>
</ul>
<p>Future research should: - Compare NYC’s compensation structures with other major cities - Analyze the effectiveness of overtime reduction strategies in similar municipal contexts - Evaluate the long-term impact of flexible work arrangements on public sector productivity - Assess the relationship between compensation caps and executive talent retention</p>
</section>
<section id="references" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> References</h1>
<ul>
<li>City of New York. (2024). Citywide Payroll Data (Fiscal Year). NYC Open Data. https://data.cityofnewyork.us/</li>
<li>Citizens Budget Commission. (2023). Seven Facts About NYC Employee Compensation. https://cbcny.org/</li>
<li>Office of the New York City Comptroller. (2023). Annual Comprehensive Financial Report. https://comptroller.nyc.gov/</li>
<li>Yang, J., &amp; Thompson, S. (2022). Public Sector Overtime Analysis: A Meta-Review. Journal of Public Administration, 45(3), 342-367.</li>
<li>Martinez, C., &amp; Davis, R. (2023). Flexible Work in Government: Case Studies from Five Cities. Urban Institute Research Report.</li>
</ul>
</section>
<section id="appendix-methodological-notes" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Appendix: Methodological Notes</h1>
<section id="methodology-details" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="methodology-details"><span class="header-section-number">10.1</span> Methodology Details</h2>
<p>This analysis used R statistical software and the following packages for data processing and visualization:</p>
<ul>
<li>dplyr, tidyr (data manipulation)</li>
<li>ggplot2 (visualization)</li>
<li>DT (interactive tables)</li>
<li>scales (formatting)</li>
</ul>
<p>The calculation methodologies for each policy included:</p>
<p><strong>Policy I (Salary Cap)</strong>: - Identified employees with total compensation exceeding the mayoral salary - Calculated the difference between actual compensation and the cap - Summed these differences to determine total potential savings</p>
<p><strong>Policy II (Overtime Reduction)</strong>: - Calculated the cost of overtime hours at 1.5x regular pay - Determined the number of full-time equivalents (FTEs) needed to cover these hours - Calculated the cost of hiring these FTEs (salary + benefits) - Computed the difference between overtime costs and new hire costs</p>
<p><strong>Policy III (Flexible Work)</strong>: - Identified employees exceeding the 20-hour monthly overtime cap - Calculated the savings from reducing their overtime to the cap level - Estimated secondary benefits based on industry research on flexible work</p>
<p>All code used in this analysis is available in the accompanying R Markdown document.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/github\.com\/LaMariah\/STA9750-2025-SPRING");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>